### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2

### ISSUE THREAD

**Issue by sephiroth-j** [stevespringett/Alpine#122] opened 2020-10-21 10:26 UTC
GA-Releases of Java 10 and newer will trigger this error because their version contain only the major version and no minor or patch level.

**GA-Release**
```
java -version
java version "15" 2020-09-15
Java(TM) SE Runtime Environment (build 15+36-1562)
Java HotSpot(TM) 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)
```
**first patch level**
```
java -version
java version "11.0.8" 2020-07-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)
```

**stacktrace from Dependency Track 3.8**
```
2020-10-21 12:15:33,402 [] WARN [org.eclipse.jetty.util.component.AbstractLifeCycle] FAILED ListenerHolder@589da3f3{FAILED}: org.dependencytrack.event.EventSubsystemInitializer: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError: null
	at alpine.Config.<clinit>(Config.java:60)
	at alpine.util.ThreadUtil.determineNumberOfWorkerThreads(ThreadUtil.java:43)
	at alpine.event.framework.EventService.<clinit>(EventService.java:51)
	at org.dependencytrack.event.EventSubsystemInitializer.<clinit>(EventSubsystemInitializer.java:60)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.eclipse.jetty.server.handler.ContextHandler$StaticContext.createInstance(ContextHandler.java:2787)
	at org.eclipse.jetty.servlet.ServletContextHandler$Context.createInstance(ServletContextHandler.java:1280)
	at org.eclipse.jetty.server.handler.ContextHandler$StaticContext.createListener(ContextHandler.java:2798)
	at org.eclipse.jetty.servlet.ListenerHolder.doStart(ListenerHolder.java:92)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:350)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:825)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:407)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:371)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at alpine.embedded.EmbeddedJettyServer.main(EmbeddedJettyServer.java:93)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at alpine.util.JavaVersion.<init>(JavaVersion.java:49)
	at alpine.util.JavaVersion.<init>(JavaVersion.java:36)
	at alpine.util.SystemUtil.<clinit>(SystemUtil.java:48)
```

**Comment by stevespringett** [comment] 2020-11-18 04:32
I'm unable to reproduce. I currently have AdoptOpenJDK 11.0.4 installed for testing and it works correctly. Are you implying that there are Java distributions that only have a major number? If so, what Java distribution only has a single major?

**Comment by stevespringett** [comment] 2020-11-18 04:37
Although I'm unable to reproduce, https://github.com/stevespringett/Alpine/commit/a6e808d6b4ac82f01ffa3fbd09336f44762b6040 should fix the issue based on the provided description of the problem.

**Comment by sephiroth-j** [comment] 2020-11-18 17:53
> I'm unable to reproduce. I currently have AdoptOpenJDK 11.0.4 installed for testing and it works correctly. Are you implying that there are Java distributions that only have a major number? If so, what Java distribution only has a single major?

Every GA release (eg. 11.0.0 or 15.0.0) of OpenJDK, Oracle JDK, AdoptOpenJDK etc. have only a major version.

AdoptOpenJDK 15+36 (15.0.0) -> https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/tag/jdk-15%2B36
OracleJDK/OpenJDK 11 -> https://www.oracle.com/java/technologies/javase/jdk11-archive-downloads.html

If your code runs on Java 9+, it is better to use [`Runtime.version()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Runtime.html#version()). See also [Runtime.Version](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Runtime.Version.html) for the format: `[1-9][0-9]*((\.0)*\.[1-9][0-9]*)*`

**Comment by stevespringett** [comment] 2020-11-18 18:02
Currently, I'm using `System.getProperty("java.runtime.version")` since DT relies on Java 8 for performance reasons. In testing, 11 is noticeably slower when processing large concurrent workloads. I'm hoping the performance improvements made since 11 (and due in 17) will be on-par or surpass the performance of Java 8. If so, I'll likely update Alpine to support modern Java versions.

**Comment by stevespringett** [comment] 2021-03-15 04:33
Closing as this issue is resolved

**Closed by stevespringett** 2021-03-15 04:33 UTC
Labels: pending release
